### ISSUE TITLE
Slide show prev next buttons

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#103]
Sometimes the previous and next buttons in the carousel on the hotel page are hard to see. We could make them bigger or a different colour so that they stand out more
![screen shot 2016-04-25 at 11 50 47](https://cloud.githubusercontent.com/assets/12450298/14781772/611dc402-0adc-11e6-9286-2101220e4758.png)

**Comment by Kumjami** [comment]
@unnderbar any design decision here? (actually the arrows are by default and I think I could customize them easily)

**Comment by Kumjami** [comment]
@jackcarlisle realized that there are packages with just one image, so slider will be disabled on this case scenario so as not to scroll on one image

**Comment by unnderbar** [comment]
![skarmavbild 2016-04-25 kl 17 38 39](https://cloud.githubusercontent.com/assets/242945/14817494/fb588ef4-0bb7-11e6-836f-80e6ec8c8ae2.png)

We'll change the design so it matches the top button in this image.

**Comment by Kumjami** [comment]
closed here https://github.com/numo-labs/isearch-ui/pull/115
