### ISSUE TITLE
Client-side-routing Requirement 

### ISSUE THREAD

**Issue by Kumjami** [numo-labs/isearch-ui#117]
In order to be able to do: https://github.com/numo-labs/isearch-ui/issues/98. 
We need a way to retrieve static data from hotels and articles. 

Use case:

1. A user shares www.isearch.com/article/all-inclusive-tenerife to a friend:

   We need to be able to retrieve data from **all-inclusive-tenerife** article in order to avoid using the current search flow. 

   This search flow would trigger a complete sequence:
   ```
front-end -> graphql service -> search handler -> create bucket -> ask cloudsearch -> publish to SNS -> etc... 
   ```
   And even being able to reproduce the search or use the URL as a search criteria. If the desired result is not in the first results page (pagination) we won't be able to "fake" normal search and make it works, we would need to deal with pagination too.

2. A user wants to save www.isearch.com/hotel/rebecca-park-gran-canaria to show it to his wife.

   Exactly the same example of above. Would be nice to be able to access to a hotel or package info despite it could not be available at the moment. Maybe saving some data about dates (url params?) would be nice, in order to make a quick request to the provider.

This could be done maybe via graphql endpoint. With a concrete search type (like autocomplete one).

**Comment by nelsonic** [comment]
According to @plaenen we are going to keep things simple to start.
`/search/{searchBucketId}/item/{itemId}` e.g: /search/12345/item/6789

This is not a *human* friendly URL, but its faster to build.

**Comment by Kumjami** [comment]
For the front-end it would be better to have: 
'/search/{bucketID}/article||hotel/{itemID}'
And the back-end wouldn't notice, so, implementing that way if nobody complain about that.

**Comment by nelsonic** [comment]
Discussion with @plaenen produced the following:

+  `/search/{bucketId}` - return list of all results e.g: `/search/123456`
+ `/article/{bucktetId}/{itemId}` - return a single article e.g: `/article/123456/C3P0`
+ `/package/{bucktetId}/{itemId}` - share a specific packageOffer e.g: `/package/123456/PMAR2D2`

where `itemId` is the item stored in **DynamoDB**.

**Comment by Kumjami** [comment]
Perfect, the routing now it's clear. 

How will be the communication with back-end and how will this data be provided by back-end has to be discussed next (endpoint, format).

**Comment by nelsonic** [comment]
@Kumjami further investigation indicates that this is not going to work because when we attempt to access a URL CloudFront/S3 attempts to find it as a *file* e.g: 
https://www.tcdl.io/isearch/0.10/index.html/search/123456 
![isearch-routing-file-fail](https://cloud.githubusercontent.com/assets/194400/15048657/5262be96-12e2-11e6-9b3d-c0a24369200b.png)

Instead, we need to use *query parameters*: 
https://www.tcdl.io/isearch/0.10/index.html?search=123456 
which will get passed through to the react app...

so we need to make it:
+  `?search={bucketId}` - return list of all results e.g: `index.html?search=123456`
+ `?search={bucketId}&article={itemId}` - return a single article e.g: `index.html?search=123456&article=MYC3P0`
+ `?search={bucketId}&package={itemId}` - share a specific packageOffer e.g: `index.html?search=123456&package=ISR2D2`

**Comment by Kumjami** [comment]
can't you set a wildcard redirect to the index.html?

**Comment by nelsonic** [comment]
@Kumjami *yes* we could but would the redirect pass the url through?

**Comment by Kumjami** [comment]
I mean a wildcard router. Every route you request will give you the index.html as response. 
I think that we could do that with hash-URL. 
E.g. /#/search/{bucketId}

**Comment by nelsonic** [comment]
Ah, yes, we could do `#/routing` ...

**Comment by Kumjami** [comment]
Using params is not routing, so we wouldn't be routing at all. We wouldn't be able to use routing logic.

**Comment by nelsonic** [comment]
@Kumjami please suggest an alternative. 👍

**Comment by Kumjami** [comment]
Hash routing for now I think is the best option. Removing the hash from routes would be really easy in case we could do wildcard routing with amazon at back-end later.

**Comment by nelsonic** [comment]
Right, but please give *examples* in your comment. :-)

**Comment by Kumjami** [comment]
Sorry :sweat_smile: 

It would be like this: 
 /#/search/{bucketId}
 /#/article/{bucketId}/{itemId}
 /#/hotel/{bucketId}/{itemId} or /#/package/{bucketId}/{itemId}

On this way we can have the react routing logic (in terms of components).

**Comment by nelsonic** [comment]
Do it. 👍

**Comment by Kumjami** [comment]
Another question @nelsonic. Buckets right now doesn't expire. But as far as I understood, you clean it somehow. 
Doing the routing based on buckets, links would eventually expire.

**Comment by nelsonic** [comment]
Yes, at the moment @plaenen has no plan to delete buckets. 
`if` we decide to "clean up" the old buckets we will implement a 404 page in the UI.

**Comment by nikhilaravi** [comment]
@Kumjami please let me know if you need help with gql queries!

**Comment by nikhilaravi** [comment]
This is the solution we're going to try http://aserafin.pl/2016/03/23/react-router-on-amazon-s3/

**Comment by Kumjami** [comment]
Due to the changes required to implement websockets (see https://github.com/numo-labs/aws-lambda-helper/issues/54)
Route will be as follow: 
`www.isearch.com/#/hotel/:userId/:bucketId/:itemid`
`www.isearch.com/#/article/:userId/:bucketId/:itemid`
`www.isearch.com/#/search/:userId/:bucketId/`
