### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#118]
TODO: 

* [x] **Hotel page:** add hotel description to the hotel page ‼️
* [x] **Searchbar:** remove hotels from the dropdown searchbar ❗️
* [x] change the 'book' button on the article page to an 'add tag' button 
* [x] **Inspiration Feed:**  include discount  price if there is one (Discount = pink price, regular price = grey price) ❗

* [x] replace price per person with the total booking price 

* [x] add home page default query tag - Denmark related - gets removed when a user performs an action to add a tag themselves
* [x] switch the kids and adults dropdowns around in the travel info section
* [x] add another button at the bottom of the hotel page that links back to spies.dk
* [x] move the content on the article and hotel pages up into the image at the top of the page
* [x] remove media query that changes the width of the grid tiles
* [x] increase vertical and horizontal spacing of the grid to 20px

**Comment by nikhilaravi** [comment]
More UI Fixes

**Hotel page**
* [ ] Remove the slide for the images on desktop and display them as a list instead
* [ ] centre the amenities text and make sure the book box doesn't overlap the description text

**Package Tile**
* [ ] Change the english words to Danish (nights, months etc)
* [ ] Check why the star rating is not showing up for some packages

** Home Page**
* [ ] Hero image with the search bar at the bottom - the page should scroll upwards when the input box is clicked (so some tiles are visible and the autocomplete box shows up)
* [ ] Add a load more button at the end of the feed to load more content
* [ ] Fade in the images after they are fully loaded
* [ ] search bar should take up more width in desktop and mobile - increase height and width and add margin between the search bar and tags
*  [ ] Add signpost svg in the header image next to the title text

**Nav Bar**
* [ ] Should show the duration of the trip in Danish 
*  [ ] the edit button should be a pen (not a / ) (icon in the UX folder)

Stretch goals!
* [ ] bouncy arrow on the home page to indicate the user to scroll down
* [ ] parallax scroll of the header image
* [ ] lift and shadow on hover over each tile - just for deskptop

**Comment by nelsonic** [comment]
Can this issue be closed...?

**Comment by nikhilaravi** [comment]
@nelsonic I've moved over the UI enhancements to a new issues so yes this can be closed!
