### ISSUE TITLE
Parse URL query/search parameters of Spies.dk url that Referred user to iSearch

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#121]
When a user comes to us from Spies.dk the URL will contain query parameters.
I've written a little parser to extract these so we can use them in our UI/Search.

> see: https://github.com/numo-labs/spies-url-parser

We need to add this to the UI so we can pre-populate the search form/parameters.

**Comment by nelsonic** [comment]
Only register the initial dataLayer if the visitor came from *spies*.

**Comment by tomgco** [comment]
@nelsonic This is implement if I am not mistaken?

**Comment by nelsonic** [comment]
Correct. 👍 
(_closing_...)
