### ISSUE TITLE
Prices changes between views

### ISSUE THREAD

**Issue by tomgco** [numo-labs/isearch-ui#141]
![screenshot from 2016-05-13 14-58-47](https://cloud.githubusercontent.com/assets/524382/15250255/c9e362ec-191b-11e6-8f59-3ec102c4bb60.png)
![screenshot from 2016-05-13 14-58-37](https://cloud.githubusercontent.com/assets/524382/15250254/c9e2d3b8-191b-11e6-8807-03eb4dcf6918.png)

**Comment by tomgco** [comment]
So this is due to the 11.798 price being for two adults and the 5.899 being `p.p.p` (price per person)

**Comment by nelsonic** [comment]
This was reported _ages_ ago. thought it had been fixed...
Apparently not. adding a regression test for it.

**Comment by nelsonic** [comment]
@emiledskar the "One Web" (TC Group) websites all use "_From 123 pp_" ...
DE: https://www.thomascook.de/
![thomascook-de-price-from-pp](https://cloud.githubusercontent.com/assets/194400/16561328/7db15444-41f0-11e6-8fa7-cc8c2f75336a.png)

BE: https://www.neckermann.be
![neckerman-be](https://cloud.githubusercontent.com/assets/194400/16563122/2fed373e-41f8-11e6-90b0-bc2980fe7377.png)

UK: https://www.thomascook.com/
![thomascook-uk-price-from-pp](https://cloud.githubusercontent.com/assets/194400/16561370/bba475d8-41f0-11e6-916e-fa0ecf4f5a13.png)

We would like to get _clarification_ from DK/SE UX as to why the _per person price_ is _not_ used on spies.dk (_if there is a UX reason we would love to see the research/findings_)

**Comment by emiledskar** [comment]
Ok guys. So I got an answer from Rasmus and we should follow spies way of presenting price per person.
If we take a look at this image from spies we can see that they are using _Pr. person_
<img width="231" alt="screen shot 2016-07-06 at 11 10 35" src="https://cloud.githubusercontent.com/assets/8721221/16613082/abdfc352-436a-11e6-85b5-c8584555a60b.png">

So this is what I propose that we do.
![image](https://cloud.githubusercontent.com/assets/8721221/16613642/64e1367c-436d-11e6-8ed4-feb404bf8ba7.png)
![pris per person 2](https://cloud.githubusercontent.com/assets/8721221/16613746/ebc8b7a0-436d-11e6-8b4c-b815ef8e99ae.png)

**Comment by nelsonic** [comment]
Thanks for _clarifying/confirming_ that @emiledskar 👍
