### ISSUE TITLE
Duration Nights not being sent to Backend 

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#142]
When viewing the Homepage:
https://s3-eu-west-1.amazonaws.com/www.tcdl.io/isearch/0.13/index.html

It *appears* as though the *default* holiday duration (*nights*) is not being sent to the backend.
As a result we are seeing super long (*and correspondingly "expensive"*) Holiday Packages.

![isearch-no-duration-in-search-means-super-long-stay-packages](https://cloud.githubusercontent.com/assets/194400/15285259/fa1932aa-1b4d-11e6-9fac-58e9daaaa5c2.png)

Is this the desired behaviour?

**Comment by tomgco** [comment]
@nelsonic Does this still happen?

**Comment by nelsonic** [comment]
@tomgco we are capturing the `duration` from the SNS message: https://github.com/numo-labs/lambda-ne-classic-package-provider/blob/3d2e649c87237d269cf62c8e2c12eb0e8a847d37/lib/parse_sns.js#L58 and it is passed on to the NE API.
