### ISSUE TITLE
Keep React components in lib folder or move into src?

### ISSUE THREAD

**Issue by nikhilaravi** [numo-labs/isearch-ui#143]
Initially we created a lib folder to keep most of the React components so they can then be easily published to npm. However, the fonts and assets for each component are also kept together so leading to unnecessary duplication and increased size of the js bundle.  I'm not sure if we plan to publish the components anymore and wanted to see what everyone thought about moving the components into src and having all the fonts and assets in one place. 

@nelsonic @jruts @Kumjami what do you think?

**Comment by Kumjami** [comment]
I agree, font and assets should be in one place.
Regarding using lib. maybe right now it makes no sense to have components there, as far as they are used once, and not published, and its so easy to publish them having them at lib as having them at any other place. 

On the other hand, I like to have something like a `components library` as far as it's well documented and well tested. 

So I would probably clean the lib folder, removing unnecessary content, but keeping it at lib. All fonts and assets together in a assets folder. And in case we would want to publish some component which require any assets just pack it there, small modification and that's it.

**Comment by nikhilaravi** [comment]
@Kumjami yes I completely agree! I've cleaned up the folder and made a folder each for assets and fonts inside src.

**Comment by nelsonic** [comment]
@nikhilaravi any reason why we don't put the fonts on S3 *once* and *exclude* them from the repo?

**Comment by nikhilaravi** [comment]
@nelsonic hmm so we'd need a copy of the fonts in the repo for developing but we could put it in the gitignore. The font files aren't included in the webpack bundle right? Also if we want to keep the initial download small we could look at code splitting with webpack https://webpack.github.io/docs/code-splitting.html

**Comment by nelsonic** [comment]
Take your pick what ever "*makes sense*" ...

**Comment by tomgco** [comment]
This conversation seems to have finished, I am closing this thread.
