### ISSUE TITLE
Refactor and Restructure the repo

### ISSUE THREAD

**Issue by nikhilaravi** [numo-labs/isearch-ui#144]
There are several components which need to be cleaned up (lots of unused props etc) and restructured. 
Once the front end routing is in place, the state in reducers can also be tidied up. 

@jruts @Kumjami @nelsonic any objections/thoughts please raise them here.

**Comment by nelsonic** [comment]
@nikhilaravi *please* go for it! 📝

**Comment by tomgco** [comment]
This still needs to happen, however as this is a long term goal and as @nikhilaravi is no longer actively working on the project I am closing this issue.
