### ISSUE TITLE
Routing fixes

### ISSUE THREAD

**Issue by nikhilaravi** [numo-labs/isearch-ui#146]
### Cloudfront 

* [x] update error page to redirect to `index.html` so hash history routing can be removed

### Components

Isearch -> index.js 
*  [x] remove the checks for 'hotelPage', 'articlePage' etc as this is now handled by the router
*  [x] remove unused props
*  [x] save the user's scroll position

### Reducers

* [x] tidy up the hotel and article reducers - 'hotelPage', 'articlePage' states, constants and actions no longer needed
* [x] remove unnecessary props in the hotel and article containers

### History

* [x] Change to BrowserHistory instead of hashHistory  - (Nikki to update cloudfront)
* [x] Add react-router-redux
* [x] Update `<Link>` tags to instead use redux actions to change the route (e.g. `push('/hotel')`) - these are provided by react-router-redux
*  [x] fix back button - should clear the hotel in view and the article in view

### Tests 

*  [ ] add tests for routing

### Questions
* Analytics tracking of user location - @nelsonic is this needed? We can add a `history.listen` function to send the location to analytics
*  If the hotel/article link is shared, when the user presses the back button should the bucket load?

**Comment by Kumjami** [comment]
@nikhilaravi We should also add the bucket search. `/:bucketId` and make it retrieve the search results of the bucket. This would answer your **2nd question**

Regarding analytics: Philip just told me to change the HTML <title> content. So we could think about making the template 'live' and grab the 'SEO content' from the `state` too.

**Comment by nikhilaravi** [comment]
@Kumjami great! So would this be for the back button on the article page? Should we check if the bucketID is the current search ID and if it is then don't reload the page but if there is not search iD (e.g someone opens a link which has been shared) then load the data from the bucket?

What needs doing in graphQL for this to be functional?

**Comment by Kumjami** [comment]
@nikhilaravi Yes, for the back button and for direct link access. 
What we should do is while rendering for the first time the ISearch component, check if there is `this.props.params.bucketId`, if so, grab the id and dispatch `saveSearchResultId` action. And then, retrieve data from dynamo as usual. 
So the flow would be: 
1. Have I `this.props.params.bucketId` ? 
    2. If yes -> update search ID and proceed as usual, retrieving data from dynamo
    3. If no -> do I have a search ID in the state?
           4. If yes -> proceed as usual, retrieving data from dynamo
           5. if no -> proceed as usual, launching a new search process

I think that nothing should be done at graphQL. This is why I've considered it kind of 'simple case'.

**Comment by nikhilaravi** [comment]
Aso do we want animations on route transition like this http://un.deter.red/dynamic-react-animations/ ?

**Comment by nikhilaravi** [comment]
Closing this issue. All tasks complete apart from routing tests which should be done by end-end tests like nightwatch.js - address in a separate issue #207
