### ISSUE TITLE
"New search" bug

### ISSUE THREAD

**Issue by Kumjami** [numo-labs/isearch-ui#149]
While trying to create a new search bucket, there is a bug if the graphql mutation params include `marketing` and `tile` filters type. 

Using the following query: 
```js
mutation startSearch($query: String) {
  viewer {
    searchResultId(query: $query) {
      id
    }
  }
}
```
And the following query variables: 
```js
{
 "query": "{\"passengers\":[{\"birthday\":\"1996-04-18\"},{\"birthday\":\"1996-04-18\"}],\"travelPeriod\":{\"departureBetween\":[\"2016-06-01\"],\"nights\":[7]},\"departureAirports\":[\"airport:master.CPH\"],\"amenity\":[\"amenity:ne.wifi\"],\"marketing\":[\"marketing:homepage.dk.spies\"],\"tile\":[\"tile:article.dk.62\"]}" 
}
```

We will get: 
```js
{
  "data": {
    "viewer": {
      "searchResultId": {
        "id": null
      }
    }
  }
}
```

If there are `tile` or `marketing` filter, but not both, the id would be a valid UUID.

**Comment by nikhilaravi** [comment]
@Kumjami ask Jimmy about this one - it might be an error from the taggable searcher in the search request handler.
