### ISSUE TITLE
Avoid hard-coding the version number in config.js

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#154]
At present the `config.js` file has the build version hard-coded:
![config js-version-hard-coded](https://cloud.githubusercontent.com/assets/194400/15402606/0075b334-1ded-11e6-8610-a5c639faf701.png)

Lets remove the manual process of having to update it... 
doing `require('pacakge.json').version.split('.')[2]` instead.

**Comment by nikhilaravi** [comment]
@nelsonic at the moment this is what I've used https://github.com/numo-labs/isearch-ui/blob/master/gulpfile.js#L22 
but I can update it to just use version from the package.json directly!

**Comment by nelsonic** [comment]
Please do. 👍

**Comment by tomgco** [comment]
This has been fixed a while back.
