### ISSUE TITLE
Send clientId / userId to the backend in GraphQL query (mutation)

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#163]
at present when I attempt to search in `0.15` s3-eu-west-1.amazonaws.com/www.tcdl.io/isearch/0.15/index.html the results are being saved to S3 with `userId` `1` e.g: https://numo-search-results.s3.amazonaws.com/ci/1/RwX0PYGadra9VMcuAALJ/LPAGREE.json

@Kumjami can you please confirm that a `userId` is being generated on the client and that:
a) it's being saved to `localStorage` (*so it can be used across sessions*)
b) it's sent to the backend in the GraphQL query.

Thanks!

**Comment by nikhilaravi** [comment]
@nelsonic @Kumjami I think this is being done. Please close the issue if you think this is satisfactory!
https://github.com/numo-labs/isearch-ui/blob/master/src/actions/search-results.js#L237
https://github.com/numo-labs/isearch-ui/blob/master/src/services/fingerprint.js#L18
https://github.com/numo-labs/isearch-ui/blob/master/src/reducers/search.js#L211

**Comment by Kumjami** [comment]
yes @nikhilaravi, you are right, I should have closed it many days ago
