### ISSUE TITLE
UI re-initialises search/tags when websocket reconnects

### ISSUE THREAD

**Issue by lennym** [numo-labs/isearch-ui#180]
When the websocket connection disconnects and reconnects the search parameters are re-initialised and the "Top inspiration" tag is displayed alongside any other tags that were already in place. A new search is carried out withe new parameters.

## Steps to reproduce

* Select a search tag and conduct a search
* Force a socket reconnect - I disabled and re-enabled wifi (Note: using Chrome devtools network condition simulator does not disconnect websockets)

## Expected:

The current search is persisted, with only previously selected tags shown.

## Actual

The "Top inspiration" tag is added and a new search is commenced.

**Comment by tomgco** [comment]
Likely happens because when a `reconnect` / `connect` event occurs we are triggering updating the ID and the tags.

**Comment by tomgco** [comment]
We could fix this by updating the tags by using a `once('connect', doUpdateTag` and the rest of the logic in a `on` listener.

**Comment by lennym** [comment]
There's a couple of issues in play here I think:

* The UI always adds the "top inspiration" tag when a socket connects, irrespective of the current search state - [code](https://github.com/numo-labs/isearch-ui/blob/master/src/services/websockets.js#L27)
* The primus room that the backchannel uses to transmit results back to the client is keyed by the connection id and not the search id, and so if the client reconnects then they have no way of receiving results for any in-progress searches.
