### ISSUE TITLE
Websocket Connection intermittent

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#192]
try: http://s3-eu-west-1.amazonaws.com/www.tcdl.io/isearch/0.15/index.html
open developer tools.
![websockets-not-connecting](https://cloud.githubusercontent.com/assets/194400/15775599/a983fb8c-297a-11e6-9fd9-08e3615fb31f.png)

**Comment by nelsonic** [comment]
Cool. thanks @tomgco 👍

**Comment by tomgco** [comment]
Was supposed to add a comment on this while closing, apparently it did not save. 

This no longer occurs, it was due to a miss-configuration in the auto-scaling group which caused web-socket connections to downgrade to http long polling.
