### ISSUE TITLE
Destination Tile Map

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#195]
> As a user, I like to see where my destination is on a *map*. 

Your mission, should you chose to accept it, is to display the destination on a mini-map given the coordinates in the `location.lat` & `location.lon` fields of a destination tile.

Spies/TC are already displaying maps e.g: [here](http://www.spies.dk/spanien/benidorm/sol-pelicanos-ocas/kort?ItemId=74800&QueryHotelCD=HALCSOLP&QueryDepID=12678&QueryCtryID=4826&QueryAreaID=0&QueryResID=74953&QueryDepDate=20160815&QueryRetDate=20160824&QueryChkInDate=20160815&QueryChkOutDate=20160824&QueryRoomAges=%7c40%2c40&QueryUnits=1&QueryAges=40%2c40&QueryType=IndependentPackage&AccBookKey=f5d1b05d-d0ad-45c1-bd81-403cc1a243fa&StrTransportKey=88688827-a34e-4382-b7ac-d8b4a45eb64b&_flowIndependentBooking=0ab6b5dd-7124-4df5-bf17-d31a5ec60435&IndependentSessionId=b0btli3xzw4u0la2xkhjrgee&SearchTime=636005702437346835&ActionName=-&TransportKey=N)

![spies-map](https://cloud.githubusercontent.com/assets/194400/15783182/073f01ca-29a5-11e6-8f3d-1005e1525150.png)

The challenge in this task is to display a *tiny* map that is still *useful* to the end-user.

**Comment by nikhilaravi** [comment]
@nelsonic is this to go on the destination tile itself? or be shown on hover/tap?

**Comment by nikhilaravi** [comment]
there are lots of options for how it could look https://react.rocks/tag/Map
