### ISSUE TITLE
Destination Tile Expanded View?

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#196]
As a user, I want to *read more* about a destination so I feel more informed.

Originally asked on *Slack*:
![destination-tile-expanded-view](https://cloud.githubusercontent.com/assets/194400/15782787/7f05f5ee-29a3-11e6-95ec-6f328b415d5d.png)

@nikhilaravi is there any *reason* we don't re-cycle the *Article* expanded view for Destination Tiles?
A few of them have quite a large block of text and several images...

CC: @jackcarlisle / @jruts / @Kumjami

**Comment by RFrijters** [comment]
we can reuse the article view for destinations for now. Unn has not left a design of the detailed view behind so lets keep it simple. when clicking on tile, a picture slide vieiw (just like hotels) on top appears with first page text and possible a map with positioning generated based on lat/long.

**Comment by nikhilaravi** [comment]
@RFrijters @nelsonic sure we can do that.
