### ISSUE TITLE
If no packages are returned for a search it spins forever

### ISSUE THREAD

**Issue by lennym** [numo-labs/isearch-ui#205]
Selecting a combination of tags which yields no package results (e.g. "Internet" and "All inclusive") causes the search loading indicator to spin forever and never returns any search results.

### Expected:

A "no results" message is shown.

**Comment by nikhilaravi** [comment]
@lennym how should the UI know there are no results? A timeout for results from the socket server? Or should the socket server send a message with an error?

**Comment by lennym** [comment]
I don't really have an answer for that. I guess we'd want to somehow propagate the fact that the package search returned no results through the results pipeline so we can stop waiting.

**Comment by lennym** [comment]
Looking at https://github.com/numo-labs/isearch-ui/blob/master/src/actions/search-results.js#L148 it seems that the result mixer could potentially return nothing if fewer than 10 packages are returned, so there is probably a need to have some kind of circuit breaker in the mixer that allows smaller result sets to be rendered after a short period of inactivity.

**Comment by tomgco** [comment]
Ideally if we are waiting for a longer period of time we should send a new request with broader search terms to try to get as many packages as possible.

**Comment by nikhilaravi** [comment]
@tomgco I think this has now been fixed because of the search complete message from the ne package provider and the display of related content when no results are returned.
