### ISSUE TITLE
Redo analytics using redux middleware

### ISSUE THREAD

**Issue by nikhilaravi** [numo-labs/isearch-ui#212]
Add a middleware that sends data from specific actions to google analytics using something like `redux-segment` or create a custom middleware. Could also add a listener to the router `history` so it can send location changes to analytics.

https://www.youtube.com/watch?v=MBTgiMLujek

**Comment by tomgco** [comment]
@nelsonic and @Kumjami Is this still needed?

**Comment by Kumjami** [comment]
@tomgco I will take a look to see how could it help us
