### ISSUE TITLE
Margin issue between packages or tiles.

### ISSUE THREAD

**Issue by jruts** [numo-labs/isearch-ui#221]
Sometimes there is an irregularity in the spacing between 2 items in the list.

![gap](https://cloud.githubusercontent.com/assets/7126237/15863750/38fc0198-2ccc-11e6-9069-26a3150efea1.png)

**Comment by lennym** [comment]
This is the filters which are not rendering correctly. #209 should resolve.

**Comment by tomgco** [comment]
> This is the filters which are not rendering correctly. #209 should resolve.

This has now been merged in.
