### ISSUE TITLE
Client should know when when there are No More (package) Results

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#228]
At present the client has no way of knowing when their search has complete, it just keeps receiving results... our plan is to send an "End" message via SNS/WebSockets that informs the user there are no more results for their query.
Client has to understand the "End Message"...
relates to: https://github.com/numo-labs/lambda-ne-classic-package-provider/issues/92

**Comment by nikhilaravi** [comment]
@nelsonic I think this has been fixed [in the ne package provider](https://github.com/numo-labs/lambda-ne-classic-package-provider/blob/master/index.js#L43) and [in the UI](https://github.com/numo-labs/isearch-ui/blob/master/src/services/websockets.js#L28). Please close the issue if you're happy with this!

**Comment by nelsonic** [comment]
Fixeded. 👍
