### ISSUE TITLE
Retrieve static content through GraphQL

### ISSUE THREAD

**Issue by Kumjami** [numo-labs/isearch-ui#238]
Right now static content is retrieved from S3 directly, but we want to make it works via GraphQL.

**Comment by nikhilaravi** [comment]
@nelsonic just to confirm - we are not going to move this functionality to GraphQL?

**Comment by nelsonic** [comment]
`Browser > GraphQL > API Gateway > Lambda (Retriever) > S3` (_3 
vs.
`Browser > S3`

The time difference is _almost_ negligible (150ms vs 300ms).
Question: what is the _advantage_ to serve the request via GraphQL...?

**Comment by Kumjami** [comment]
I though it was something we wanted to do. I guessed it was maybe for tracking purposes or whatever. 
I think it is not needed. 
(I just didn't understand well)

So closing. 
Thanks @nikhilaravi and @nelsonic :+1:
