### ISSUE TITLE
Destinations need location data - lat & lon

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#245]
In order for the destination tiles to display the correct data,  they need the correct coordinates to be sent through from the backend. Currently the location of the map and marker is hard coded.

**Comment by nelsonic** [comment]
@jackcarlisle the destination tiles are already stored with Lat/Lon e.g: 
https://numo-taggy.s3.amazonaws.com/ci/tile/destination/tile%3Adestination.dk.108055.json
For some reason they are not being correctly displayed in `DESTINY` ...
