### ISSUE TITLE
Analytics fixes and improvements.

### ISSUE THREAD

**Issue by Kumjami** [numo-labs/isearch-ui#249]
Here there is a list of fixes and improvements needed to track analytics data correctly. 
[Inspirational search analytics ref doc](https://drive.google.com/drive/u/1/folders/0B1aHHUZuc5YOT1ZPR0xEVjlrbm8)

- [x] **Impresions** 
Impressions regarding articles and tiles has been lost. 

- [x] **Products click events** 
While clicking some search result item we need to emit a event.

- [x] **Tags** 
Review tags tracking and ensure that adding and removing tags events are being well tracked.

- [x] **Spies.dk links** 
We need to remove `utm_content` parameter from the spies.dk hotel links and add `landingfrom =inspirational_search`.
**Note**: *we are already doing it at our side, but spies.dk is modifying url params, so we have nothing else to do here*

- [x] **Spies.dk link click** 
After clicking a hotel link to spies.dk an `add to cart` event has to be triggered. 

- [x] **Destination tile events**
Destination tiles should have the same events that articles or hotels.
      - Impresions
      - Clicks
      - Views

- [x] **Customer landing data**
The `customer landing` event should trigger only while coming from spies.dk.

- [x] **Referrer**
Articles, hotels and destinations should have the proper referrer. Right know the referrer is not being changed. As it's a SPA, the referrer it's always the referrer of the index. 
**NOTE:** *Not for now*

- [x] **Meta templating**
The HTML meta title should be the article, hotel or destination title.

- [x] **User preferences** 
User preferences should be tracked: country, dates, persons number, etc...

**Comment by nelsonic** [comment]
@Kumjami thanks for working on this. it's important. ⬆️

**Comment by Kumjami** [comment]
@nelsonic I will be doing PR for each point, maybe someone could contain more than one, but my idea is doing step by step, and refactor analytics code (it's a little bit messy right now)

**Comment by Kumjami** [comment]
Btw, I've created an **analytics** branch, and my idea is submits pull requests with each point to this branch. After everything is ok, open a PR to master. So each checkpoint would be completed while merging to analytics branch. And the issue would be closed after merging analytics branch to master. 
Pros: organization
Cons: the final merge could be harder, and the increment is not so *smooth*
What do you think? @nelsonic
