### ISSUE TITLE
Usabilla feedback

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#252]
* [x] When you search for tags, they drop down below the input field. After clicking on one of the tags you have to click on the plus sign as well to get the results. It would be better if the tiles below were updated immediately after clicking the tag in the drop down list.
* [x] A pointing hand should be shown when mousing over the plus button.
* [x] If we enable update of the tiles when the user clicks on a dropdown element, then the plus button will be redundant.
* [x] A hand should be shown when mousing over the 'X' to the right of search tags when the user wants to remove them.
* [x] ~~The current headline indicates that the users should already be at a stage where they have decided where to go. It contradicts the idea that this tool should be usable for people who does not necessarily know where to go. Therefore we have to find a different, more open headline. **(waiting on decision to be made about new headline)**~~
* [x] If I edit the number of persons that are travelling, click search and go to edit again, then the info that I changed the last time has not been saved.
* [x] ~~Is there a reason why the top bar (with the Spies logo etc.) is not visible until you scroll down? _The reason was to get the user to the search results as quickly as possible and then change their search criteria at a later stage if neccessary_ **(discuss with UX designer)**~~
* [x] ~~It is not clear to the user if the '1 week, 2 adults' selection has impact on the search results. Does the search results change if you select e.g. 2 children as well? If they do, we should somehow explain this to the user. **(discuss with UX designer)**~~
* [x] It is unclear what happens after clicking the 'Search' button when you have changed number of pax etc. What does clicking 'Search' result in? 
* [x] Duplicate suggestions for the same search result i.e., I get for example 3 Barcelona suggestions and they yield different results
* [x] When i add a filter, the ui jumps back to the search box. pretty annoying. i want to see the results. now i need to scroll down overtime i add a filter.
* [x] when i have read an article and added the tag, it show up like i haven't added the tag but i did. please check

**Comment by tomgco** [comment]
Everything seems to have been completed, closing.
