### ISSUE TITLE
default image for tiles when there isn't one available

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#304]
![screen shot 2016-06-21 at 16 02 23](https://cloud.githubusercontent.com/assets/12450298/16234590/deaa1ea6-37c9-11e6-9e60-46fa6d6b518f.png)
Do we have a default image that we can use when a tile doesn't have one?

**Comment by nelsonic** [comment]
A default image would look a bit repetitive ... let's #AskRasmus ...
relates to: #302

**Comment by jackcarlisle** [comment]
sorry didn't see #302

**Comment by nelsonic** [comment]
@jackcarlisle we just need to get it _fixed_ tomorrow.
