### ISSUE TITLE
Title obscures input field on mobile

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#305]
The header text is overlapping the input field when the keyboard is open which making it difficult to see what you are typing.

<img style="-webkit-user-select: none; cursor: zoom-in;" src="https://cloud.githubusercontent.com/assets/8721221/16260912/a27dffa6-3869-11e6-93c3-1323ea485266.png" width="250">

**Comment by nelsonic** [comment]
@emiledskar  we *think* this is fixed...
![screenshot_20160622-173809](https://cloud.githubusercontent.com/assets/194400/16275066/52f86d04-38a0-11e6-8bbb-a9f214d7ffd6.png)
Please re-test and confirm.
