### ISSUE TITLE
Query parameters for predefined entry point

### ISSUE THREAD

**Issue by jruts** [numo-labs/isearch-ui#316]
We should be able to add a query parameter to the url so that we can add tags via this way.

E.g. if we would have this `url: http://inspiationalsearch.spies.dk?search=family` I would like to see the 'Family' tag as the default tag instead of `Top inspiration`.

The search query parameter should allow multiple search tags separated by a semicolon.

You can use the autocomplete query with 1 result to translate the query param into the actual tag:
```js
query {
  viewer {
    autocomplete(text: "Family", size: 1) {
      items {
        name
        label
      }
    }
  }
}
```

**Comment by lennym** [comment]
Would the expected workflow for this be as follows:

* perform a query to the autocomplete with whatever search term is provided
* add the first tag that is returned
* do a search

I assume this would leave the existing functionality around reset buttons and removing the "default" tag when adding new tags? i.e. it's not a "default" tag in the same way as "Top inspiration" is, it is simply a short-cut to a pre-filled search.

**Comment by jruts** [comment]
@lennym the expected workflow would be:

1) On spies.dk there are some tiles .e.g. "family holidays"
2) Someone clicks that tile and gets redirected to the inspirational search app with "Family Holiday" in the query parameters
3) When loading the isearch component we will trigger an autocomplete with 1 result for the query parameters, and those results will indeed replace the "default" tag.

So your expectations are indeed accurate.
