### ISSUE TITLE
Specify Node Version for UI (Pre-built binaries not found for node-zopfli node@4.3.2)

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#318]
When attempting to install all the dependencies using Node.js v4.3.2 (the lambda version)
![isearch-ui-node-zopfli](https://cloud.githubusercontent.com/assets/194400/16384320/5d3403da-3c80-11e6-87c1-b1b2ec510dd2.png)

Error:
```sh
Pre-built binaries not found for node-zopfli@1.4.0 and node@4.3.2 (node-v46 ABI) (falling back to source compile with node-gyp)
```

See: https://codeship.com/projects/140431/builds/16011162 `npm install` section.
Note: the tests still pass but deployment would fail because `node-zopfli` is required for compression.
This was first reported by @lennym 

> The apparent solution is simply to update your _local_ version of Node.js. 
However we want a solution that prevents others from seeing this error (e.g. specify the `engines` in `package.json` or in Readme?)

**Comment by lennym** [comment]
I don't think this is an actual problem, it just compiles a binary at install time. It should still install fine.

**Comment by lennym** [comment]
To expand - the problem I had was that the compilation step failed on account of an outdated version of `node-gyp` on my machine. This is just the developers logging things as `ERR` which should really be `WARN`.

**Comment by nelsonic** [comment]
@lennym cool. closing. 👍
