### ISSUE TITLE
Poor quality article images

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#353]
When I search for Spanien and then click on the article about Madrid the image is pixelated

<img width="783" alt="screen shot 2016-07-04 at 09 49 10" src="https://cloud.githubusercontent.com/assets/12450298/16556222/a7ca8720-41d0-11e6-881e-b72ad50af681.png">

**Comment by tomgco** [comment]
This would be the content that is being inserted into arty and desty right?

**Comment by jackcarlisle** [comment]
@tomgco yeah!

**Comment by tomgco** [comment]
Maybe this is something that we can raise with Roy, etc.

**Comment by emiledskar** [comment]
I will talk to Martin in Denmark about this tomorrow (Wednesday), he might have a replacement image with better quality.

**Comment by emiledskar** [comment]
Removed image as it was a profile picture from the source of the article
