### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#36]

**Comment by jackcarlisle** [comment]
![5481508216_667daacfcd_o 1](https://cloud.githubusercontent.com/assets/12450298/13823520/c7afbfe0-eba1-11e5-9f08-2e8eada89d53.jpg)

**Comment by jackcarlisle** [comment]
![lk1008_2_53](https://cloud.githubusercontent.com/assets/12450298/14560385/62833d9a-0307-11e6-8a23-a0d1793d4e72.jpg)

**Comment by jackcarlisle** [comment]
![lk1001_2_53](https://cloud.githubusercontent.com/assets/12450298/14560416/8f5ab97e-0307-11e6-968b-5ac3baf17a6a.jpg)

**Comment by nikhilaravi** [comment]
the background image has now been decided and added to the home page.
