### ISSUE TITLE
Scroll page down onload when auto-tagging from query string

### ISSUE THREAD

**Issue by lennym** [numo-labs/isearch-ui#370]
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/?search=city-break

### Expected Behaviour

User is automatically scrolled down to their search results when a search term has been defined in the query string so that they can see the searched-for tag, and the corresponding results.

### Actual Behaviour

User stays at the top of the page, so they do not know that a search has already been carried out since they cannot see the resulting tag, or any results.

**Comment by Kumjami** [comment]
Actually, scroll while focus has been lost too, hasn't it?
