### ISSUE TITLE
Placeholder Suggestions Cycle

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#375]
- Tags Searched: n/a
- Page URL: http://localhost:8080/

### Screen Shot

![screen shot 2016-07-12 at 09 28 08](https://cloud.githubusercontent.com/assets/12450298/16760343/21f60fb8-4813-11e6-8ad4-50099d05f17e.png)

### Expected Behaviour
As a user I would like to know what I am able to search for in the search bar. The search bar should prompt or inform me in some way.

### Actual Behaviour
The search bar has a placeholder that feels ambiguous. As a user it is currently it is unclear what can be searched for.

- Logs ID: 29e98d52-e8d3-479b-b6a1-61541f231218
- Tracey ID: 9198ec90-480a-11e6-8b4f-8782cd46b4c0

**Comment by emiledskar** [comment]
@jackcarlisle: As this is a part of the stuff I'm going to test with users, you can put this on hold for now. I will get back to you with words/phrases to use and how it should look and behave.

**Comment by jackcarlisle** [comment]
@emiledskar sorry I didn't see this! I've added a simple implementation that I can change if required
