### ISSUE TITLE
Tile overflow & margin issue

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#376]
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: Spanien, n/a
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/

### Screen Shot
![Screenshot](https://cloud.githubusercontent.com/assets/8721221/16758420/a86de8e2-4811-11e6-8ba0-3ed2a853c5ca.png)
![Screenshot](https://cloud.githubusercontent.com/assets/8721221/16761216/77bed6b2-481f-11e6-8587-f3e1d8db381e.png)

### Expected Behaviour
Tile should have equal margins on both sides.
Image should be contained inside tile.

### Actual Behaviour
Left side of tile has a margin but the right side does not.
Image leaks outside of tile container.

### Further Information
First screenshot is from device toolbar in google developer mode. Here the issue is that the image is overflowing the container. 
The second screenshot is on a mobile device and here the problem is that the tile has 5px margin on the left side but not on the right.

**Comment by emiledskar** [comment]
This is still visible for me on resolution 360 x *

**Comment by jackcarlisle** [comment]
@emiledskar will fix today

**Comment by jackcarlisle** [comment]
![screen shot 2016-07-27 at 10 07 15](https://cloud.githubusercontent.com/assets/12450298/17170663/2306e520-53e5-11e6-9740-4fbba0c312a9.png)
