### ISSUE TITLE
Autosuggestion style and behavior

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#385]
### What to do?

* [x] The default style of the dropdown should follow [mobile](http://zpl.io/Z1Ea1QQ), [desktop](https://zpl.io/E5v1h), [on hover state for desktop](https://zpl.io/ZA73JI), [in case of tags longer than width of container](https://zpl.io/1fwj0G)
* [x] The dropdown with autosuggestions should be visible when input field has focus. [mobile](http://zpl.io/Z1aeEl7), [desktop](https://zpl.io/Zs7L1b)
* [x] On a search with no result the dropdown should look like [mobile](http://zpl.io/1u9f0u), [desktop](https://zpl.io/Z1J94bT)

##### Default style
- By using this design we can show more tags in less vertical screen space.
- We will get past the problem with keyboard overlapping dropdown on mobile devices.

##### Autosuggestion on focus
- We will teach the user how to use the search and what to search for. 
- We can influence what users search for.

##### Autosuggestion on a search with no result
- This will help users recover from searching for invalid keywords

**Comment by Kumjami** [comment]
From the first point, only https://app.zeplin.io/project.html#pid=57862d8c724b75ab5d685d18&sid=57888b77d1a4e2d444787678 is missing

**Comment by Kumjami** [comment]
@emiledskar Question: 
May the dropdown default autosuggestions when focusing make users believe that only this tags are available?
May they think that they can only filter in the displayed list (which actually is really sort)?

**Comment by emiledskar** [comment]
@Kumjami I don't think it will because of the label "Popular search terms" above the suggestions. But I will pay attention to this next time I test it with users.

**Comment by tomgco** [comment]
This is in the latest ci deployments
