### ISSUE TITLE
Travel attributes selection popover

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#388]
### What to do?
Create a popover according to [this](https://zpl.io/Z1Bpx5v) 

### Why?
The user will remain in the same context when they change these attributes making it easier to understand.

### Further Information
A desktop design will be added, same functionality but some minor changes in UI.
This change will be accompanied by changing location and design of the button/link to open the popover.

**Comment by emiledskar** [comment]
@jackcarlisle could you make the popover close when user clicks Opdater?

**Comment by jackcarlisle** [comment]
@emiledskar sure! Will be active in the next release
