### ISSUE TITLE
Beta banner

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#397]
A banner on the top of the page that indicates that the product is in a BETA stage.

[Mobile](https://zpl.io/1YbFXb)
[Mobile top bar + banner](https://zpl.io/15KVPM)
[Desktop](https://zpl.io/Z1ci2XJ)
[Desktop top bar + banner](https://zpl.io/ZF5dOe)

**Comment by nelsonic** [comment]
@emiledskar clicking on the Zeplin links requires us to login however we do not have accounts on Zeplin... would you mind sharing the login with us in Slack or uploading screenshots? (_thanks_)

**Comment by nelsonic** [comment]
![isearch-beta-banner](https://cloud.githubusercontent.com/assets/194400/16913543/17c7e492-4ce3-11e6-9805-c7fd841fee7a.png)
