### ISSUE TITLE
Non-active articles are visible in UI

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#398]
Some articles that are set to be non-active in Arty is still visible in the UI.
Seems that this is fixed by setting articles to active -> save & update -> non-active -> save & udpate

**Comment by lennym** [comment]
This is fixed as described above for articles which are indexed since the code fix was applied

### To Do

[ ] Run a script to force re-indexing of all tiles to ensure any tiles which were marked inactive before the code fix shipped show correctly.

**Comment by lennym** [comment]
@emiledskar Yes. Should be done fairly soon.
