### ISSUE TITLE
PhantomJS ?

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#399]
Just checkout `master` and ran `npm install` which installed PhantomJS:
![isearch-ui-phantomjs](https://cloud.githubusercontent.com/assets/194400/16911343/d10c6292-4cd5-11e6-8158-4c62a279213a.png)

@lennym are we using Phantom for something? (_I can't find it in the list of `scripts` or the Readme..._)

**Comment by lennym** [comment]
Yes, the unit tests now run in karma-phantom so that they can execute with real browser APIs.

**Comment by nelsonic** [comment]
Cool. any chance we can add a few lines to the Readme explaining this? 
I know it seems _obvious_ to experienced, but not everyone will be familiar with Karma+Phantom ...
