### ISSUE TITLE
Varying content for same search

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#401]
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: Spanien
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=sbwcub
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Expected Behaviour
When I search for e.g. Spanien I expect to see the same content for both searches, only difference should be in how the content is sorted.

### Actual Behaviour
Sometimes the same search does not give the same result. 
e.g.
[First search - no articles included](https://app.usabilla.com/feedback/item/e8b4542b8149996477cb9e7be254b3911d76728b)
[Second search - articles included](https://cloud.githubusercontent.com/assets/8721221/16913713/ccc59fac-4cec-11e6-92f3-1cf9ed1ea74e.png)

### Further Information
[Similar issue](https://app.usabilla.com/feedback/item/27469bf717f1f9494a611718565305c0edc54e82) where search occasionally returns no result

**Comment by tomgco** [comment]
I can't seem to reproduce this issue. Does it still happen for you?

**Comment by Kumjami** [comment]
@emiledskar @tomgco how is it going? should we just close the isssue?

**Comment by emiledskar** [comment]
@Kumjami I think we can close it. I haven't observed this issue after the fixes done during wed/thu.
