### ISSUE TITLE
Change in React Auto-suggest Component means change in suggestion class name

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#404]
As a result of changing React components to [`react-autosuggest`](https://github.com/numo-labs/isearch-ui/commit/e7606f8498cf8ce071bff4611f8ecb2f68347a86)

Old:
![isearch-autocomplete-old](https://cloud.githubusercontent.com/assets/194400/16917974/b7530768-4cfb-11e6-983e-0de7cfc81ab5.png)

New:
![isearch-autocomplete-new](https://cloud.githubusercontent.com/assets/194400/16917982/bd8e3af8-4cfb-11e6-9b58-4dad83b8d6eb.png)

The Nightwatch tests are looking for the _old_ CSS class ... we need to update it. 

Also, why is it listed as a [`devDependency`](https://github.com/numo-labs/isearch-ui/blob/a24fb9262341eb1faa658888ed6dff5f39a80c09/package.json#L88) instead of `dependency` ...?

**Comment by Kumjami** [comment]
My fault in the dependency mistake :sweat:
