### ISSUE TITLE
Autosuggestion Suggestions ... Croatia?

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#405]
Where are we getting our list of search suggestions from?

At present one of the suggestions is `Croatia...` see: https://github.com/numo-labs/isearch-ui/blob/ee08c12018105c4121c3c60ecb48868e87687b28/lib/search-bar/index.js#L141
![isearch-suggest-croatia](https://cloud.githubusercontent.com/assets/194400/16919915/69e83482-4d03-11e6-9e93-3bd4b42c56f9.png)

However, when I attempt to search for that tag/destination I get:
![isearch-we-dont-have-croatia-packages](https://cloud.githubusercontent.com/assets/194400/16919922/6f8ac968-4d03-11e6-8cec-5854bd94d610.png)

Is there a way derive the list of autosuggest suggestions based on the number of packages/tiles we have for that particular result?

**Comment by jackcarlisle** [comment]
@emiledskar which default suggestions should we cycle through for the placeholders?
