### ISSUE TITLE
Same tiles in result and suggestion

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#410]
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: All inclusive (Date set to 30/5-16)
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=bp732o
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot
![9](https://cloud.githubusercontent.com/assets/8721221/16944189/b03ffa72-4d9f-11e6-9652-8c857c979470.png)

### Expected Behaviour
I expect the section "You might also like this" to contain other articles that I might find interesting based on my search.

### Actual Behaviour
Some of the articles are the same as the search result.

**Comment by jackcarlisle** [comment]
<img width="1611" alt="screen shot 2016-07-20 at 13 45 25" src="https://cloud.githubusercontent.com/assets/12450298/16986768/44e5c8a6-4e80-11e6-947b-6a943fab11f9.png">

Resulting articles from the same search

**Comment by jackcarlisle** [comment]
<img width="1602" alt="screen shot 2016-07-20 at 13 45 16" src="https://cloud.githubusercontent.com/assets/12450298/16986776/5598ee08-4e80-11e6-97b7-d2634221b4cc.png">

Related articles from the same search with no duplicates

**Comment by emiledskar** [comment]
@jackcarlisle yep, I have also checked and it works as intended
