### ISSUE TITLE
No result and no indication of why, empty result container

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#411]
- Tags Searched: Storbyferie
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=bp732o
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot
![Screenshot](https://cloud.githubusercontent.com/assets/8721221/16944548/644841b8-4da1-11e6-82bf-3483a2bb6090.png)

### Expected Behaviour
If no result could be found I expect to see information about "no content could be found" and the section of suggested content.

### Actual Behaviour
The result area is empty.

### Debug Information
(For developers, delete if not applicable, otherwise see https://github.com/numo-labs/isearch-ui#debugging-tracing-requests)

- Logs ID: 71764de4-315a-4b4d-b422-4db0cc46f942
- Tracey ID: 50bad630-4d90-11e6-b2b3-574f749e765f

**Comment by tomgco** [comment]
This has been resolved.
