### ISSUE TITLE
Result content is not cleared when tag is removed.

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#412]
- Tags Searched: Spanien
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=bp732o
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot
![Screenshot](https://cloud.githubusercontent.com/assets/8721221/16947019/ca464874-4dac-11e6-86e2-7222a7695290.png)

### Expected Behaviour
When I remove the tag I expect the result content to disappear and the default content to come back.

### Actual Behaviour
I can remove the tag but the result content is still there

**Comment by lennym** [comment]
@emiledskar 

Does this mean that I should not be able to remove the default tag when it is displayed?

If not, then what should happen when the default tag is removed?

**Comment by emiledskar** [comment]
@lennym In the new design for v 24 the default tag is removed but the content/feed is the default one. So the user will se the same content but no tag. I think this is a valid solution for this version also, to just remove the default tag "top inspiration" but have the content for the default state the same as it is today.
