### ISSUE TITLE
Title positioned over BETA banner

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#415]
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: n/a
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=bp732o
- Web Browser: http://www.whatsmybrowser.org/b/10WBIGP
- Phone: Sony xperia Z5 compact

### Screen Shot
![screenshot](https://cloud.githubusercontent.com/assets/8721221/16948457/080e6e0e-4db5-11e6-9e21-0038fec20f15.png)

### Information
Title is positioned over the BETA banner.

**Comment by tomgco** [comment]
Can someone confirm that is still is an issue?

**Comment by emiledskar** [comment]
Yes, this still occurs on my phone.

**Comment by tomgco** [comment]
@jackcarlisle or @Kumjami could you look into this as it affects production?

**Comment by emiledskar** [comment]
I could try to use google dev tools and inspect why this is happening on my phone. I don't have any micro usb cable available right now but I can take a look tonight at home.

**Comment by tomgco** [comment]
> I could try to use google dev tools and inspect why this is happening on my phone. I don't have any micro usb cable available right now but I can take a look tonight at home.

The resolution reported is:

Browser size 360 x 512
Screen size 360 x 640 (Retina)

So it should be possible to emulate

**Comment by tomgco** [comment]
I have reproduced this by setting a custom device screen size of `Browser size 360 x 512` in google dev tools @emiledskar

**Comment by jackcarlisle** [comment]
<img width="396" alt="screen shot 2016-07-26 at 12 08 21" src="https://cloud.githubusercontent.com/assets/12450298/17135843/aead900e-5329-11e6-849e-21a0bc5cdb5d.png">
