### ISSUE TITLE
Grey background on select elements

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#416]
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: n/a
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=bp732o
- Web Browser: http://www.whatsmybrowser.org/b/10WBIGP

### Screen Shot
![image](https://cloud.githubusercontent.com/assets/8721221/16949688/7643da88-4dbc-11e6-9d24-0deec0e80d80.png)

### Information
Select element has a grey background.

**Comment by jackcarlisle** [comment]
<img width="430" alt="screen shot 2016-07-20 at 13 32 02" src="https://cloud.githubusercontent.com/assets/12450298/16986461/7e17da26-4e7e-11e6-9e27-1b6cfabd38dc.png">
