### ISSUE TITLE
Reset dropdown suggestions on text clear

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#417]
Tags Searched: n/a
Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=bp732o
Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot

![image](https://cloud.githubusercontent.com/assets/8721221/16950098/c09ea94e-4dbe-11e6-9793-87fac5af6b00.png)
After clearing text
![image](https://cloud.githubusercontent.com/assets/8721221/16950122/dd0e6de4-4dbe-11e6-91b4-629226926667.png)

### Expected Behaviour
Removing all the text from the input field should reset the state of the dropdown to the default state were we show "Popular search terms".

### Actual Behaviour
If I have searched for something and then clears all the text. The dropdown will be filled with suggestions based on the last search.

**Comment by emiledskar** [comment]
This might be connected to #421

**Comment by tomgco** [comment]
This is now fixed in `1.0.24`

**Comment by emiledskar** [comment]
This happens to me still. [Video](https://drive.google.com/open?id=0BwJ2qQvXEjayczJJbzFKLThVLTA)

**Comment by tomgco** [comment]
> This happens to me still. Video

I don't seem to have access to this video =[

**Comment by lennym** [comment]
I am not able to replicate this. Is there a particular key/event/interaction sequence you use to replicate?

**Comment by emiledskar** [comment]
@lennym This is what I do: Start typing Bar, then press backspace until field is empty. Then I press outside input field to shift focus. When I then set focus on the input field the suggestions that pops up is based on "Bar"

**Comment by lennym** [comment]
Aha! Got it now. The blur/focus is necessary to replicate, and is what I was missing before.
