### ISSUE TITLE
Dropdown should close when focus is lost

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#420]
- Tags Searched: n/a
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=bp732o
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot
![image](https://cloud.githubusercontent.com/assets/8721221/16950429/8512cd22-4dc0-11e6-9da7-42723f0759cd.png)

### Expected Behaviour
When I click somewhere on the site so that the input field loses focus the dropdown should close itself.

### Actual Behaviour
The dropdown stays open when focus is lost.

**Comment by Kumjami** [comment]
@emiledskar I can't reproduce it (http://inspirationalsearch.spies.dk/isearch/1.0.24/)

**Comment by emiledskar** [comment]
@Kumjami seems to be fixed
