### ISSUE TITLE
Dropdown does not open on focus

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#421]
- Tags Searched: n/a
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=bp732o
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot
This is easier to explain with a short video.
[link to video](https://drive.google.com/open?id=0BwJ2qQvXEjayWTFkelpMZXpMNHc)

### Expected Behaviour
The dropdown should open again when the input field gets focus.

### Actual Behaviour
Dropdown does not open until I start to type.

**Comment by emiledskar** [comment]
This might be connected to #417

**Comment by Kumjami** [comment]
Already fixed: http://inspirationalsearch.spies.dk/isearch/1.0.24/#/?_k=8x8i87

[Commit](https://github.com/numo-labs/isearch-ui/commit/716ccc80873de1491ffe1e9833b45d4d7bd411e8)
