### ISSUE TITLE
Tag "City Trip" returns 0 results

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#422]
- Tags Searched: Storbyferie (City Trip)
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=bp732o
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot
![screenshot](https://cloud.githubusercontent.com/assets/8721221/16951122/f57b748a-4dc3-11e6-9f82-d186836d1abf.png)
![screenshot](https://cloud.githubusercontent.com/assets/8721221/16951121/f57b07c0-4dc3-11e6-8124-c470636b48f9.png)

### Expected Behaviour
I expect to see the articles that according to taggable UI are connected to this tag.

### Actual Behaviour
No result is found.

### Debug Information
(For developers, delete if not applicable, otherwise see https://github.com/numo-labs/isearch-ui#debugging-tracing-requests)

- Logs ID: 264b6e86-aa72-492d-9d21-9ad04df9e262
- Tracey ID: 9a650d10-4db2-11e6-96e7-4f053081d30e

**Comment by tomgco** [comment]
Fixing loads of things to fix this... Still haven't nailed down the reason why yet, but it could be a disparity between what has been deployed in production and what has been deployed in ci.

Continuing to investigate...
💭 💭 💭

**Comment by tomgco** [comment]
Ok we now have packages showing. However we are still not seeing tiles

**Comment by nelsonic** [comment]
Status: Tom is re-deploying his fix for this... 🎱

**Comment by lennym** [comment]
This is now resolved.
