### ISSUE TITLE
Translate text on button inside hotel detail view

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#423]
- Tags Searched: n/a
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/hotel/13ace9d0-4db4-11e6-96e7-4f053081d30e/8117?_k=phasui

### Screen Shot
![screenshot](https://cloud.githubusercontent.com/assets/8721221/16951427/3d9c5f44-4dc5-11e6-883f-4305fb77f109.png)

### Information
Change the text of the button to "Se pris og bestil".

**Comment by emiledskar** [comment]
@jackcarlisle Translation should be on the button at the bottom also. And remove the text above that button.
![screenshot](https://cloud.githubusercontent.com/assets/8721221/16951830/f5de6312-4dc6-11e6-88cb-bee64769d822.png)

**Comment by nelsonic** [comment]
Booking button Top:
![isearch-booking-button-top](https://cloud.githubusercontent.com/assets/194400/16982200/81919862-4e66-11e6-8761-4acd95db5cf1.png)

Booking button Bottom:
![isearch-booking-button-bottom](https://cloud.githubusercontent.com/assets/194400/16982202/85eb21a8-4e66-11e6-8cfb-a3d274eb1524.png)
