### ISSUE TITLE
Remove old travel attribute button

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#433]
### Screen Shot
![screenshot](https://cloud.githubusercontent.com/assets/8721221/16982329/7eeb4334-4e6f-11e6-80e2-d85e6fbd6eeb.png)

### Information
Remove the old travel attribute button from the header. This button is now replaced with the new additions to the search box.

**Comment by jackcarlisle** [comment]
@emiledskar should the paxmix text remain or should it be removed as well?

**Comment by emiledskar** [comment]
@jackcarlisle yes. If we later on finds evidence that the user wants this information visible, we will add it somewhere around the search box.

**Comment by jackcarlisle** [comment]
<img width="389" alt="screen shot 2016-07-20 at 13 30 40" src="https://cloud.githubusercontent.com/assets/12450298/16986392/326cc816-4e7e-11e6-9c15-04b0177b1289.png">
