### ISSUE TITLE
Click outside popover (on overlay) should close it 

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#434]
### Screen Shot

![Screenshot](https://cloud.githubusercontent.com/assets/8721221/16982431/feff45ac-4e6f-11e6-91e1-076f26862a08.png)

### Information
User should be able to click outside of the popover to close it. i.e. make click on overlay close popover.

**Comment by jackcarlisle** [comment]
[video](https://drive.google.com/drive/u/0/folders/0BwJ2qQvXEjayVzdOU205MDZiaGs) of fix

**Comment by tomgco** [comment]
@emiledskar Can you close this when you confirm it is working as intended on ci.

**Comment by tomgco** [comment]
Actually I can confirm it is working.
