### ISSUE TITLE
Outbound & Inbound dates are the same for some packages

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#444]
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: Spanien
- Page URL: http://localhost:8080/
- Web Browser: http://whatsmybrowser.org/b/8M4HR2D
- Mobile make & model (if applicable): n/a

### Screen Shot

![screen shot 2016-07-20 at 16 34 05](https://cloud.githubusercontent.com/assets/12450298/16993055/bec34ca2-4e99-11e6-94a6-c76f97f095aa.png)

### Expected Behaviour
Outbound date should be before inbound date
### Actual Behaviour
Some packages have the same inbound and outbound date even though the package is for longer than one day e.g. 7 nights
### Debug Information
(For developers, delete if not applicable, otherwise see https://github.com/numo-labs/isearch-ui#debugging-tracing-requests)

- Logs ID: a6638cb9-57d7-4723-abb4-d61a8e94338f
- Tracey ID: d17ea7c0-4e8e-11e6-8944-c9ab1eb17e0f

**Comment by emiledskar** [comment]
Users has also reported this as a bug with usabilla [(link)](https://app.usabilla.com/feedback/item/ed0d2d589fd7a86b5ff22e5a17342f7e4de6ab69)

**Comment by tomgco** [comment]
This has now been fixed in CI
