### ISSUE TITLE
Popular Tags

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#450]
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: n/a
- Page URL: localhost:8080
- Web Browser:  http://whatsmybrowser.org/b/8M4HR2D
- Mobile make & model (if applicable): n/a

### Screen Shot

<img width="484" alt="screen shot 2016-07-21 at 16 25 49" src="https://cloud.githubusercontent.com/assets/12450298/17028593/f17f7122-4f5f-11e6-8b0a-4a0c6dce3a87.png">

### Expected Behaviour
Populat tags should be: Storbyferie, London, Shopping, Rom, Seværdigheder, Barcelona
### Actual Behaviour
Popular tags are: Spanien, All Inclusive, Lollo & Bernie, Internet
### Debug Information
- Logs ID: 6f2c7c4c-8cf4-41ed-af3c-c7e6a2e0a5f6
- Tracey ID: ¯\_(ツ)_/¯

**Comment by emiledskar** [comment]
@jackcarlisle these tags should also be suggested in the dropdown when no results could be found. This dropdown...
![image](https://cloud.githubusercontent.com/assets/8721221/17056310/d8bcb556-5012-11e6-9f95-c2a5ccb45bb4.png)

**Comment by jackcarlisle** [comment]
@emiledskar cool I'll change them today
