### ISSUE TITLE
Packages in suggestion section

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#454]
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: London, Mallorca, Barcelona
- Page URL: http://inspirationalsearch.spies.dk/isearch/1.0.24/#/?_k=zzy2tx
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot

[Video](https://drive.google.com/open?id=0BwJ2qQvXEjaydE93aVo0OFVVNWM)

### Information
Packages has started to show up in the suggested content section. Seems to be the same packages every time.

**Comment by lennym** [comment]
This has been identified as being caused by the addition of a link between the homepage tag (which is also used to populate "related" content) and the Turkey geo tag.
