### ISSUE TITLE
Do not let users select a date from a time period that has passed.

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#465]
### Screen Shot
![image](https://cloud.githubusercontent.com/assets/8721221/17102202/e173b560-5278-11e6-87e2-5c4611a51c38.png)

### Expected Behaviour
I should only be able to select dates from "today" and forward.

### Actual Behaviour
I can select a date from a time period that has passed.

**Comment by emiledskar** [comment]
Are we using any vendor plugin for this date selection dropdown? If that is the case the design/style for disabled dates might already be included so it would be nice to know.

**Comment by tomgco** [comment]
> Are we using any vendor plugin for this date selection dropdown? If that is the case the design/style for disabled dates might already be included so it would be nice to know.

I believe it is a react component and has the feature, I am looking at that now.
