### ISSUE TITLE
"No hotels warning in this time period" is not displayed when it should

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#466]
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: Barcelona & date 3/5-2016
- Page URL: http://inspirationalsearch.spies.dk/isearch/1.0.24/#/?_k=d7ro9y
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot
![image](https://cloud.githubusercontent.com/assets/8721221/17103393/6363ee28-527e-11e6-926f-feeb07104fbf.png)

### Expected Behaviour
When no packages are visible in result I expect to see the warning that tells me that I need to change the time period to find hotels.

### Actual Behaviour
I see no warning.

**Comment by tomgco** [comment]
@emiledskar I have just ran the same search and was able to see packages coming back, could it be that they just took a long while before they started showing?

**Comment by emiledskar** [comment]
@tomgco And you selected the date 3/5-2016? I have tested again and I can see no packages nor any warning.

Anyhow I think it would be strange to see packages returned for this search as this date has passed :) The reason I search with that specific date was that I wanted to see if the warning would be shown.

**Comment by tomgco** [comment]
> @tomgco And you selected the date 3/5-2016? I have tested again and I can see no packages nor any warning.
> 
> Anyhow I think it would be strange to see packages returned for this search as this date has passed :) The reason I search with that specific date was that I wanted to see if the warning would be shown.

Ahh, missed that as a step.
