### ISSUE TITLE
Currency Symbol needs to be correct for locale

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#47]
https://www.tcdl.io/isearch/0.4/index.html
![numo-search-results-currency-symbol](https://cloud.githubusercontent.com/assets/194400/13937664/ae8d5ba0-efbe-11e5-931a-1622d1c4ef33.png)

**Comment by jackcarlisle** [comment]
Currency format on spies.dk 

![screen shot 2016-04-25 at 17 46 14](https://cloud.githubusercontent.com/assets/12450298/14791429/b360b3d8-0b0d-11e6-993c-e34ad6b2209f.png)
