### ISSUE TITLE
Different content for London tag

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#470]
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: London
- Page URL: http://inspirationalsearch.spies.dk/isearch/1.0.24/#/?_k=d7ro9y
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Information
The London tag in the "Popular tags" dropdown and the London tag I get when I start typing Lon.. returns different results content. See video for further explanation.

### Video
[Link](https://drive.google.com/open?id=0BwJ2qQvXEjayaUJXNFNoZXExM00)

### Expected Behaviour
To see the same result when I search for London

**Comment by lennym** [comment]
There are (kind of) two geo tags for London:

* `geo:geonames.2643743` - the "London" geo tag
* `geo:geonames.2648110` - the "Greater London" geo tag.

The suggested search term actually [adds the latter tag](https://github.com/numo-labs/isearch-ui/blob/master/lib/search-bar/defaultSuggestions.js#L27)

To fix I would suggest adding `geo:geonames.2643743` instead in the code linked above.
