### ISSUE TITLE
Add text to top bar back arrow

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#480]
### Screen Shot
[Screenshot](https://zpl.io/27xIwk)

### Information
Add a text that says "Tilbage" next to the back arrow to make it more visually prominent

**Comment by jackcarlisle** [comment]
@emiledskar should the text be clickable as well or just the arrow?

**Comment by emiledskar** [comment]
@jackcarlisle The text should also be clickable

**Comment by jackcarlisle** [comment]
![screen shot 2016-07-27 at 11 04 32](https://cloud.githubusercontent.com/assets/12450298/17171825/3f455e56-53ea-11e6-94d8-53bc28163d5e.png)
