### ISSUE TITLE
new style for "you might also like this" section header

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#481]
### Screen Shot Mobile
[Zeplin link](https://zpl.io/Zw0AAk)

##### New
![image](https://cloud.githubusercontent.com/assets/8721221/17171400/e08e2d00-53f0-11e6-94cb-c678c6a754e5.png)

##### Current
![image](https://cloud.githubusercontent.com/assets/8721221/17171228/00ea8f0e-53f0-11e6-89da-d133677c83cd.png)

### Screen Shot Desktop
[Zeplin link](https://zpl.io/Z27Bn3F)

##### New
![image](https://cloud.githubusercontent.com/assets/8721221/17171250/22e47bce-53f0-11e6-9138-aa430f354817.png)
##### Current
![image](https://cloud.githubusercontent.com/assets/8721221/17171256/2cd26696-53f0-11e6-972c-3dbc22ad5e29.png)

### Information
Change the look of the "header" for the _you might also like this_ section so that it will be easier to notice so that the users know why this content might not be even close to what they searched for.

**Comment by lennym** [comment]
Am I right to assume that the blue border in the desktop version and the blue circle in the mobile version are screenshot artefacts, and not part of the actual design?

**Comment by emiledskar** [comment]
@lennym :) Yes, they just tagged along from Zeplin when I took the screen shot.

**Comment by jackcarlisle** [comment]
![screen shot 2016-07-27 at 11 57 22](https://cloud.githubusercontent.com/assets/12450298/17173229/64c656ba-53f1-11e6-9a5a-ba0d408047f7.png)
desktop

**Comment by jackcarlisle** [comment]
![screen shot 2016-07-27 at 11 57 43](https://cloud.githubusercontent.com/assets/12450298/17173232/6c0d9a28-53f1-11e6-8987-82faa40407e6.png)
mobile
