### ISSUE TITLE
Article view should look as the preview does in Arty

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#483]
- Page URL: http://inspirationalsearch.spies.dk/isearch/1.0.24/#/article/7b999020-53e0-11e6-bcd5-0797d5336b46/tile:article.dk.63?_k=jx9u5y
- Article: Ex. Restauranter i Paris

### Live on page
![image](https://cloud.githubusercontent.com/assets/8721221/17172057/b1b52dc8-53f3-11e6-8f9a-743119c85eac.png)

### Preview in Arty
![image](https://cloud.githubusercontent.com/assets/8721221/17172220/507829ba-53f4-11e6-919a-2277f7fc2862.png)

### Information
The structure and look of the article view is different when you preview it inside Arty and what you see when it is live on the page. The text and image structure should follow what we see in Arty.

**Comment by jackcarlisle** [comment]
![screen shot 2016-07-27 at 12 23 19](https://cloud.githubusercontent.com/assets/12450298/17173875/4aa40490-53f5-11e6-96c8-c7f0386bf623.png)
Updated article view

**Comment by emiledskar** [comment]
@jackcarlisle Could you make the preamble left aligned?

**Comment by jackcarlisle** [comment]
![screen shot 2016-07-27 at 13 19 00](https://cloud.githubusercontent.com/assets/12450298/17174922/b8c58172-53fc-11e6-9298-4ac4583fa7ba.png)
Update
