### ISSUE TITLE
Hotel Page Update (mobile & desktop)

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#487]
To ensure a full fix for the issue being opened can you please provide:

### Description

Change in layout on the hotel page for both mobile and desktop (see links below)

### New layout

[Mobile](https://zpl.io/ZHq1x6)
[Desktop](https://zpl.io/217wsz)

**Comment by jackcarlisle** [comment]
![screen shot 2016-07-27 at 16 51 54](https://cloud.githubusercontent.com/assets/12450298/17182182/922902a0-541a-11e6-8eed-fec10c124bad.png)
Desktop

**Comment by jackcarlisle** [comment]
![screen shot 2016-07-27 at 16 52 16](https://cloud.githubusercontent.com/assets/12450298/17182195/9c858174-541a-11e6-8465-02789ffd88f1.png)
Mobile

**Comment by Kumjami** [comment]
@jackcarlisle Why `Strand` only has a "m" without value? Should we remove the "m" and put "-" instead?, or just there is something wrong rendering it?

**Comment by emiledskar** [comment]
@Kumjami Good catch, I think the we should follow the same guidelines as spies.dk. They use "Nej" on the question you can answer No to, like Pool, Bar, Restaurant etc. When it comes to _Strand_ and _Lokalt centrum_ I think we should go with the "-" symbol

**Comment by jackcarlisle** [comment]
@Kumjami @emiledskar this has been fixed now, our list of amenities was always rendering distance to beach even if it wasn't part of the list for that hotel

**Comment by jackcarlisle** [comment]
<img width="398" alt="screen shot 2016-07-28 at 11 53 19" src="https://cloud.githubusercontent.com/assets/12450298/17210463/1af8730e-54bb-11e6-8420-742c801625b9.png">

**Comment by Kumjami** [comment]
@jackcarlisle @emiledskar As far as the related PR is closed, I think this could also be closed.
