### ISSUE TITLE
Clear the placeholder from the input field when it has focus

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#491]
### Expected Behaviour
Clear the placeholder from the input field when it has focus.

### Actual Behaviour
On focus the placeholder keeps changing. Seems to be confusing some users and making them unsure if they should type something.

**Comment by jackcarlisle** [comment]
<img width="966" alt="screen shot 2016-07-29 at 10 26 21" src="https://cloud.githubusercontent.com/assets/12450298/17243897/eebdbb20-5576-11e6-8155-4c0f921de95b.png">

**Comment by Kumjami** [comment]
@jackcarlisle should it be closed?

**Comment by jackcarlisle** [comment]
@Kumjami yeah I'll close now
