### ISSUE TITLE
Analytics Undefined destinationName

### ISSUE THREAD

**Issue by Kumjami** [numo-labs/isearch-ui#494]
To ensure a full fix for the issue being opened can you please provide:

- Page URL: http://inspirationalsearch.spies.dk/isearch/1.0.24/#/hotel/b6fdf3b0-5497-11e6-9930-b7cc24f653e2/8755

### Screen Shot

![image](https://cloud.githubusercontent.com/assets/8338963/17206962/94b1ef26-54b2-11e6-9c9b-b66a1a59cf1f.png)

### Expected Behaviour

DestinationName should have the human friendly destination name code.

### Actual Behaviour

DestinationName is equal to the string `undefined`

### Further Information

This is being received directly from the back-end as a string with value `undefined`

**Comment by tomgco** [comment]
s/undefined/unavailable/

This isn't a bug but intended behaviour for when a provider does not have a destination name. This is up to the analytics team to decide what information they wish to receive instead.

**Comment by Kumjami** [comment]
@tomgco Yes tom, removing `bug` flag, but letting it here just not to forget

**Comment by tomgco** [comment]
From slack: 

```
ok then! No biggie! I was not aware of that. From an analytics perspective it is not a big deal, we can use detination code instead, which is actually available
```
