### ISSUE TITLE
Limit suggestion dropdown to 3 rows on mobile

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#495]
### Screen Shot
![image](https://cloud.githubusercontent.com/assets/8721221/17207187/9cfd1ed4-54b3-11e6-8bee-727dc0e22eaf.png)

### Expected Behaviour
Dropdown should be limited to 3 rows on mobile to take in to consideration the small screen area and the user's keyboard.

### Actual Behaviour
The dropdown has a default of 5 rows.

**Comment by Kumjami** [comment]
I guess it's only the viewport what you want to limit to 3 rows. I mean, right now, there is a scroll if the height of all the possible suggestions exceed the 5 rows limit. 
I assume we want to keep this behavior. (So there will be the possibiliti to scrolling down)

**Comment by jackcarlisle** [comment]
@Kumjami yes I think it's only the viewport

**Comment by Kumjami** [comment]
while limitting to 3 rows height, the no resutls looks like : 

![image](https://cloud.githubusercontent.com/assets/8338963/17243893/4024cba4-557f-11e6-9616-de6478bcbbe8.png)

the default suggestions: 

![image](https://cloud.githubusercontent.com/assets/8338963/17243904/552e0d62-557f-11e6-8c25-696863120b9d.png)

**Comment by Kumjami** [comment]
Just for pointing it out. 
In landscape: 
![image](https://cloud.githubusercontent.com/assets/8338963/17244112/8189d2be-5580-11e6-84d7-565c0d25bec4.png)

**Comment by emiledskar** [comment]
@Kumjami What I want is that on screens with smaller viewport there should be max 3 rows of suggestions (6 suggestions) + potential titles e.g "Populære søgeord" and "Din søgning gav ingen resultanter...". We can keep the scroll inside the suggestions area. 
Ideally we would have a design for search that is better fitted for landscape but as we stand now with little time left I think we should not bother putting time on fixing this.

**Comment by Kumjami** [comment]
@emiledskar Then, this is ready https://github.com/numo-labs/isearch-ui/pull/499 to be reviewed/merged.  :wink:
