### ISSUE TITLE
Popover styling issue

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#522]
- Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot

![image](https://cloud.githubusercontent.com/assets/8721221/17737834/2a1bfde0-648f-11e6-901d-23bfe62f22ce.png)

### Expected Behaviour
Popover container should resize itself to hold the content.

### Actual Behaviour
The button "Opdater" is positioned outside the popover container when a user selects 1 or more kids and the date selection boxes are added.

**Comment by jackcarlisle** [comment]
<img width="945" alt="screen shot 2016-08-17 at 16 21 39" src="https://cloud.githubusercontent.com/assets/12450298/17742276/42500e3a-6497-11e6-83e6-19d7cf57bd57.png">
<img width="990" alt="screen shot 2016-08-17 at 16 21 50" src="https://cloud.githubusercontent.com/assets/12450298/17742281/46ab6916-6497-11e6-9dfc-61eba410ce0d.png">
