### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#54]
These tasks refer to the sections in: https://drive.google.com/drive/u/0/folders/0B1aHHUZuc5YOT1ZPR0xEVjlrbm8
+ [x] **Tracking of Tags** - tags added by the user in the ui should be sent to `dataLayer`. where a tag contains multiple words these should be separated by an underscore e.g: `'sunwing_family_resort'`
+ [x] **Tile removal** - when a tag/tile is dismissed we should send that event. 
+ [x] **On Initial Page Load** - the query the person had in spies.dk should be passed over to the iSearch and sent on to GA. this requires us accessing the http referrer. see: https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer > https://www.tcdl.io.s3.amazonaws.com/isearch/analytics-test.html
+ [x] **‘Add Vacation Preferences’ Interactions**
+ [x] **Travel Info Updates**

**Comment by nelsonic** [comment]
Steps to check that initial page load Analytics are working:
+ Visit: https://www.tcdl.io.s3.amazonaws.com/isearch/analytics-test.html
![tc-analytics-test-click-the-link](https://cloud.githubusercontent.com/assets/194400/15227247/2847ba16-187e-11e6-9aab-720972688e3e.png)
Open your developer tools Console, then Click the link!

+ This will take you to V0.12 where you will see:
![tc-analytics-test-showing-data-sent-to-datalayer](https://cloud.githubusercontent.com/assets/194400/15227310/73ef6496-187e-11e6-9229-59d7b7a30ff9.png)

**Comment by tomgco** [comment]
@nelsonic @Kumjami Can this be closed?
