### ISSUE TITLE
Deployment from CodeShip

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#60]
At present deployment is not configured on CodeShip ... (*we are having to* ***manually*** *deploy from localhost*)

![numo-isearch-ui-does-not-get-deployed-by-codeship](https://cloud.githubusercontent.com/assets/194400/14204664/adcdafe8-f7fd-11e5-9609-2ab81ecf65bc.png)

**Comment by nelsonic** [comment]
I added `npm run deploy` to: https://codeship.com/projects/140431/deployment_branches/128889
please confirm it works next time a PR is merged into `master`.

**Comment by tomgco** [comment]
We are now deploying using a CI pipeline.
