### ISSUE TITLE
Null as city/area

### ISSUE THREAD

**Issue by unnderbar** [numo-labs/isearch-ui#61]
<img width="833" alt="skarmavbild 2016-04-04 kl 10 29 19" src="https://cloud.githubusercontent.com/assets/242945/14242256/a1eeab00-fa50-11e5-9b96-4baa4e386801.png">

Version 0.5.

**Comment by nelsonic** [comment]
well spotted @unnderbar

**Comment by unnderbar** [comment]
We still have this bug in version 0.7

**Comment by jackcarlisle** [comment]
fixed!
