### ISSUE TITLE
Webpack test config?

### ISSUE THREAD

**Issue by nikhilaravi** [numo-labs/isearch-ui#63]
The webpack dev config settings allows react components in the lib folder to be used like npm modules, however the tests are not run with webpack (just mocha with a babel compiler) so the components cannot be resolved in the tests. This means the modules have to be required with their full paths (e.g. ../../../lib/component) which defeats the point of the webpack dev config!!!

Maybe we should add a webpack test config with similar settings and run the tests this way?

**Comment by tomgco** [comment]
> The webpack dev config settings allows react components in the lib folder to be used like npm modules, however the tests are not run with webpack (just mocha with a babel compiler) so the components cannot be resolved in the tests. This means the modules have to be required with their full paths (e.g. ../../../lib/component) which defeats the point of the webpack dev config!!!
> 
> Maybe we should add a webpack test config with similar settings and run the tests this way?

This seems to conflict with the recent changes that @lennym has carried out. I will close this issue as testing these as node modules doesn't make sense due to being used exclusively on the front-end.
