### ISSUE TITLE
Hide/Remove Non-relevant Search Results from UI when New Search Performed

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#74]
As a user I expect to see *relevant* results when I perform a search in the UI. 
e.g: `Spain` results when I search for `spain` ... not Turkey

https://www.tcdl.io/isearch/0.7/index.html
![isearch-ui-displays-turkey-for-spain-search](https://cloud.githubusercontent.com/assets/194400/14605934/d6160a36-0572-11e6-9f86-35e369e8e994.png)

**Comment by nikhilaravi** [comment]
@nelsonic I think this has been fixed now. Can I close this issue?
