### ISSUE TITLE
Long response times without system status

### ISSUE THREAD

**Issue by unnderbar** [numo-labs/isearch-ui#76]
<img width="1440" alt="skarmavbild 2016-04-18 kl 15 58 06" src="https://cloud.githubusercontent.com/assets/242945/14606627/62711056-057e-11e6-8074-9d7a7a5ecff3.png">

After I made a mistake it take too long before the system gives me any feedback that it's thinking. 

Solution: Some type of spinner to indicate that it's thinking.

**Comment by nikhilaravi** [comment]
@unnderbar a spinner has been added so I'm closing this issue! :)
