### ISSUE TITLE
Maldives doesn't work

### ISSUE THREAD

**Issue by unnderbar** [numo-labs/isearch-ui#77]
We don't seem to have all destinations in the system. Maldives doesn't work.

<img width="1440" alt="skarmavbild 2016-04-18 kl 15 48 54" src="https://cloud.githubusercontent.com/assets/242945/14606784/fbd1310e-057e-11e6-8524-1acfc7ad1329.png">

**Comment by nelsonic** [comment]
@unnderbar do we *have* Maldives ***Classic*** **Package holidays** on Spies.dk ?

**Comment by unnderbar** [comment]
Might be dynamic package now that I think of it. We don't have those yet?

**Comment by alehandra1702** [comment]
No we have only classic packages

**Comment by nelsonic** [comment]
I don't know... when I search for `"Maldives"` we have 3 hotels in the Tagging system, but when I attempt to search for Classic packages I don't see any results... 😞

**Comment by nikhilaravi** [comment]
@nelsonic there still doesn't seem to be any results for Maldives - any idea why?

**Comment by nelsonic** [comment]
Good question. we need to do a stack trace for this search query. Please pair with @tomgco to debug.

**Comment by tomgco** [comment]
@nikhilaravi When you are free lets go through this. 

I have had a quick look into an example request that I have made:
