### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by unnderbar** [numo-labs/isearch-ui#78]
As soon as I've clicked in the text input field we suggest a couple of filters. This is a great opportunity for us to promote things and get people to choose All Incluseve etc.

<img width="375" alt="skarmavbild 2016-04-18 kl 16 39 43" src="https://cloud.githubusercontent.com/assets/242945/14607980/35b69382-0584-11e6-8343-f25f1343299d.png">

**Comment by nikhilaravi** [comment]
@unnderbar i'm going to work on this today! :)

**Comment by nikhilaravi** [comment]
@unnderbar this is now working!
