### ISSUE TITLE
Filter: Travelling with Kids > Desired behaviour after clicking "No"

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#82]
Visit: https://www.tcdl.io/isearch/0.7/index.html
Scroll till you find the `ARE YOU TRAVELLING WITH KIDS ?` *filter*:
![isearch-kids-filter-click-no](https://cloud.githubusercontent.com/assets/194400/14636801/819a8dca-0625-11e6-8560-b6e34dbe8c9a.png)

When you click "No" what do you *expect*?

At the moment the UI/Search is not being updated to reflect the filtering:
![isearch-2-children-after-clicking-no-to-kids](https://cloud.githubusercontent.com/assets/194400/14636858/d76b2322-0625-11e6-9248-8bcc35ca2260.png)

I would *expect* the `2 children` to be removed from the search.
@unnderbar your thoughts?

**Comment by tomgco** [comment]
No longer applicable.
