### ISSUE TITLE
Keep/remove filtering on the front end

### ISSUE THREAD

**Issue by nikhilaravi** [numo-labs/isearch-ui#95]
Need to make a decision about removing/improving client side filtering when a tag is selected. 

i.e If someone searches for wifi, there may already be hotels on the page which have wifi so we could immediately filter for these and display them and also issue a new query to the backend for more results. This would give the users a faster response.

This filtering is already possible for amenity tags but need to decider whether on not to implement it for geo tags as well or remove this functionality completely.

**Comment by nikhilaravi** [comment]
Filtering on the front end has now been removed.

**Comment by nelsonic** [comment]
Given that the NE Metasearch API can take up to 8 seconds to respond,
If done right front-end filtering could offer a *massive* UX benefit. 😞 
But it "*makes sense*" to exclude it if we aren't going to invest in making it work properly.
