### ISSUE TITLE
Fix rendering of articles

### ISSUE THREAD

**Issue by nikhilaravi** [numo-labs/isearch-ui#97]
Some articles have very long titles - need to be limited to a fixed number of words/characters. 
The size of the images also need fixing! At the moment 
`object-fit: cover` is used to get the images to take up the tile width, but they do not have the correct dimensions.

**Comment by Kumjami** [comment]
Do we have a concrete amount of characters?  
Regarding images, do we have a specific images aspect ratio or size? or just the best way to fit them

**Comment by Kumjami** [comment]
As discussed with @unnderbar, images should be provided on the correct size/aspect-ratio to fit the design. So Images problems have nothing to do with the implemention.

**Comment by nikhilaravi** [comment]
@Kumjami has this been fixed now?

**Comment by Kumjami** [comment]
@nikhilaravi as far as I understood, we have nothing to do with this, images should be provided in a correct format and the font was changed, so maybe we should close this issue.

**Comment by nikhilaravi** [comment]
@Kumjami ok sure

**Comment by Kumjami** [comment]
If agree I'm closing it.
