### ISSUE TITLE
Client-Side Routing

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#98]
As a user I want to be able to share content with friends/family when I am researching my next holiday.
To enable this user behaviour, we need to add (*client-side*) routing to the UI.

sample urls:
+ /articles/10-places-to-visit-in-china
+ /hotels/heartbreak-hotel
+ /places/gran-canaria

This means our (*client-side*) router needs to *understand* the different types of content based on the first section of the path and lookup the item of content by the second section of the url.

At present we are storing `articles` in CloudSearch, but the articles are not being *served* by CloudSearch to the UI, instead they are being stored in DynamoDB by `lambda-tile-provider` see: https://github.com/numo-labs/lambda-tile-provider#current-content 
this means we do not *currently* have a way to *directly* lookup a content/article tile in CloudSearch ...

**Comment by Kumjami** [comment]
We would need a lambda or API to retrieve the content directly from CloudSearch as far as we don't want to submit a new search query while accessing this content by URL
